import React from 'react';
import { View, ScrollView, StyleSheet, TouchableOpacity, Linking } from 'react-native';
import { Card, Text } from 'react-native-paper';
import { SafeAreaView } from 'react-native-safe-area-context';
import Markdown from 'react-native-markdown-display';
import { Issue, IssueStatus } from '../../lib/types/dagster';
import { useTheme } from '../ThemeProvider';
import EmptyState from '../EmptyState';

interface IssueDetailScreenProps {
  navigation: any;
  route: { params?: { issue?: Issue } };
}

const SAFE_LINK_SCHEMES = ['http:', 'https:', 'mailto:'];
const handleLinkPress = (url: string): boolean => {
  const lowered = (url || '').trim().toLowerCase();
  if (SAFE_LINK_SCHEMES.some((s) => lowered.startsWith(s))) {
    Linking.openURL(url).catch(() => {});
    return false;
  }
  return false;
};

const statusPalette = (status: IssueStatus, theme: any): { bg: string; fg: string } => {
  const upper = (status || '').toUpperCase();
  if (upper === 'OPEN' || upper === 'IN_PROGRESS') {
    return { bg: theme.dark ? '#3d2a1a' : '#fff3e0', fg: theme.dark ? '#ffb74d' : '#e65100' };
  }
  if (upper === 'RESOLVED' || upper === 'CLOSED') {
    return { bg: theme.dark ? '#1f3a24' : '#e8f5e9', fg: theme.dark ? '#81c784' : '#1b5e20' };
  }
  return { bg: theme.colors.surfaceVariant, fg: theme.colors.onSurfaceVariant };
};

// Issue bodies generated by Compass include two sections that don't belong in
// the mobile experience:
//   1. "### Related Links" — duplicates the linked-runs card above AND links
//      to web URLs that drop the user into an external browser login flow.
//   2. A trailing "*Created from Dagster+ Issue: [...](url)*" footer that the
//      web UI hides; on mobile it bounces the user out to log into the web.
// Strip both before rendering. Other body content is left alone.
const sanitizeIssueMarkdown = (md: string | null | undefined): string => {
  if (!md) return '';
  let out = md;
  out = out.replace(/\n*###\s+Related Links[\s\S]*?(?=\n###|\n---|$)/g, '\n');
  out = out.replace(/\n*---\s*\n*\*Created from Dagster\+ Issue:[\s\S]*$/g, '');
  return out.trim();
};

const buildMarkdownStyles = (theme: any) => ({
  body: { color: theme.colors.onSurface, fontSize: 14, lineHeight: 20 },
  paragraph: { marginTop: 0, marginBottom: 8, color: theme.colors.onSurface },
  heading1: { color: theme.colors.onSurface, fontSize: 20, fontWeight: '700', marginTop: 8, marginBottom: 4 },
  heading2: { color: theme.colors.onSurface, fontSize: 18, fontWeight: '700', marginTop: 8, marginBottom: 4 },
  heading3: { color: theme.colors.onSurface, fontSize: 16, fontWeight: '700', marginTop: 6, marginBottom: 4 },
  strong: { fontWeight: '700', color: theme.colors.onSurface },
  em: { fontStyle: 'italic', color: theme.colors.onSurface },
  link: { color: theme.colors.primary, textDecorationLine: 'underline' },
  code_inline: { fontFamily: 'Menlo', fontSize: 12, color: theme.colors.primary },
  code_block: {
    fontFamily: 'Menlo', fontSize: 12,
    backgroundColor: theme.colors.surfaceVariant, color: theme.colors.onSurfaceVariant,
    padding: 8, borderRadius: 4, marginVertical: 6,
  },
  fence: {
    fontFamily: 'Menlo', fontSize: 12,
    backgroundColor: theme.colors.surfaceVariant, color: theme.colors.onSurfaceVariant,
    padding: 8, borderRadius: 4, marginVertical: 6,
  },
  bullet_list: { marginVertical: 4 },
  ordered_list: { marginVertical: 4 },
  list_item: { marginVertical: 2 },
});

const IssueDetailScreen: React.FC<IssueDetailScreenProps> = ({ navigation, route }) => {
  const { theme } = useTheme();
  const issue = route?.params?.issue;

  React.useLayoutEffect(() => {
    if (issue) {
      navigation.setOptions({ headerTitle: `#${issue.publicId}` });
    }
  }, [navigation, issue]);

  if (!issue) {
    return (
      <SafeAreaView style={[styles.flex, { backgroundColor: theme.colors.background }]} edges={['bottom']}>
        <EmptyState
          icon="error-outline"
          title="Issue unavailable"
          description="Open this issue from the list to see its details."
        />
      </SafeAreaView>
    );
  }

  const pill = statusPalette(issue.status, theme);
  const author = issue.createdBy?.displayName || issue.createdBy?.email || 'Unknown';
  const body = sanitizeIssueMarkdown(issue.asMarkdown || issue.description || '');

  return (
    <SafeAreaView style={[styles.flex, { backgroundColor: theme.colors.background }]} edges={['bottom']}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <Text style={[styles.title, { color: theme.colors.onSurface }]}>{issue.title}</Text>

        <View style={styles.metaRow}>
          <View style={[styles.pill, { backgroundColor: pill.bg }]}>
            <Text style={[styles.pillText, { color: pill.fg }]}>{issue.status}</Text>
          </View>
          <Text style={[styles.meta, { color: theme.colors.onSurfaceVariant }]}>by {author}</Text>
        </View>

        {issue.linkedObjects && issue.linkedObjects.length > 0 && (
          <Card style={[styles.section, { backgroundColor: theme.colors.surface }]}>
            <Card.Content>
              <Text style={[styles.sectionTitle, { color: theme.colors.onSurface }]}>Linked runs</Text>
              {issue.linkedObjects.map((run) => (
                <TouchableOpacity
                  key={run.id}
                  onPress={() => navigation.navigate('RunDetail', { runId: run.id })}
                  style={styles.linkRow}
                >
                  <Text style={[styles.linkText, { color: theme.colors.primary }]}>
                    {run.runId.slice(0, 8)}
                  </Text>
                  {run.repositoryOrigin?.repositoryLocationName && (
                    <Text style={[styles.meta, { color: theme.colors.onSurfaceVariant }]}>
                      {run.repositoryOrigin.repositoryLocationName}
                    </Text>
                  )}
                </TouchableOpacity>
              ))}
            </Card.Content>
          </Card>
        )}

        {body ? (
          <Card style={[styles.section, { backgroundColor: theme.colors.surface }]}>
            <Card.Content>
              <Markdown style={buildMarkdownStyles(theme) as any} onLinkPress={handleLinkPress}>
                {body}
              </Markdown>
            </Card.Content>
          </Card>
        ) : null}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  flex: { flex: 1 },
  scrollContent: { padding: 12 },
  title: { fontSize: 18, fontWeight: '700', lineHeight: 24, marginBottom: 8 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  pill: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 12 },
  pillText: { fontSize: 11, fontWeight: '700', letterSpacing: 0.3 },
  meta: { fontSize: 13 },
  section: { marginBottom: 12 },
  sectionTitle: { fontSize: 13, fontWeight: '700', marginBottom: 6, letterSpacing: 0.3 },
  linkRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 6 },
  linkText: { fontSize: 14, fontWeight: '600' },
});

export default IssueDetailScreen;
